language: rust
os:
    - linux
    - osx
before_install:
    - sudo add-apt-repository -y ppa:kalakris/cmake
    - sudo apt-get update -qq
install:
    # CMake, require newer version, than in Travis
    - sudo apt-get install libXxf86vm-dev cmake
    # SDL2
    - curl -O http://www.libsdl.org/release/SDL2-2.0.0.tar.gz
    - tar -xzvf SDL2-2.0.0.tar.gz
    - (cd SDL2-2.0.0 && ./configure && make && sudo make install)
script:
    - cargo build -v
